[package]
name = "test_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rdkafka = "0.28.0"
tokio = { version = "1.18", features = ["full"] }
futures = "0.3"  # Make sure this is included